spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    # Server should not register with Eureka
    register-with-eureka: false
    # Server should not fetch registry from Eureka
    fetch-registry: false
